# Generated by Django 3.1.1 on 2020-09-13 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_post_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created']},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='pub_date',
            new_name='created',
        ),
    ]
